### PR TITLE
make compatible with laravel 5.6

### PR DESCRIPTION
**Pull request by romanmartushev**
Not sure how to target v1.3.0 but here is the changes to make this possible #6

### CODE REVIEW

**Comment by natenolting** [comment]
So what version would this be then when it's tagged? We already have one that is for 5.6. Maybe we should make branches for each version rather than tagging.

**Comment by castillo-n** [comment]
this was solved

**Comment by natenolting** [comment]
@castillo-n so merge this in or not?

**Comment by castillo-n** [comment]
@natenolting there is no need, the cool thing about tags is that you can remove them and attach them to a different commit, which is what I did

**Pull request closed without merging**
